# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
    ]
