# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0002_auto_20160329_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='site_id',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='rate.Institute'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='site_id',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='rate.StudentGroup'),
        ),
    ]
