# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_remove_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerow',
            name='coefficient',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tablerow',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablerow',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
