# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_auto_20160414_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerow',
            name='coefficient',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='point',
            field=models.FloatField(default=0, null=True),
        ),
    ]
