# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_dropdwon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='general_server_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
