# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0007_auto_20160404_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathsVPN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathsvpn_vpn_path', models.TextField(max_length=200)),
                ('pathsvpn_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.General')),
            ],
            options={
                'db_table': 'pathsvpn',
            },
        ),
    ]
