# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_pathsvpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='revoke',
            name='certs_general',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vpn.General'),
            preserve_default=False,
        ),
    ]
