# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0009_revoke_certs_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='general_project_status',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
